from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class FieldMapping:
    target: str
    source_header: str = ""
    source_index: int = 0


def generate_vba(
    mappings: list[FieldMapping],
    header_row: int,
    data_start_row: int,
    output_sheet_name: str = "CLEANED_INVOICE_PL",
    lookup_mode: str = "header",
    fixed_title: str = "",
) -> str:
    use_header_lookup = lookup_mode == "header"
    target_headers = [mapping.target for mapping in mappings]
    source_headers = [mapping.source_header for mapping in mappings]
    fallback_cols = [mapping.source_index for mapping in mappings]

    return f'''Option Explicit

' Generated by Invoice / Packing List VBA Generator.
' Paste this module into Excel VBA, then run CleanInvoicePackingList.

Public Sub CleanInvoicePackingList()
    Const OUTPUT_SHEET_NAME As String = {_vba_string(output_sheet_name)}
    Const HEADER_ROW As Long = {max(header_row, 1)}
    Const DATA_START_ROW As Long = {max(data_start_row, 1)}
    Const USE_HEADER_LOOKUP As Boolean = {_vba_boolean(use_header_lookup)}
    Const FIXED_TITLE As String = {_vba_string(fixed_title)}

    Dim wsSrc As Worksheet
    Dim wsOut As Worksheet
    Dim targetHeaders As Variant
    Dim sourceHeaders As Variant
    Dim fallbackCols As Variant
    Dim sourceCols() As Long
    Dim lastRow As Long
    Dim outRow As Long
    Dim r As Long
    Dim i As Long

    Set wsSrc = ActiveSheet
    Set wsOut = GetOrCreateSheet(OUTPUT_SHEET_NAME)
    wsOut.Cells.Clear

    targetHeaders = {_vba_array_strings(target_headers)}
    sourceHeaders = {_vba_array_strings(source_headers)}
    fallbackCols = {_vba_array_numbers(fallback_cols)}
    ReDim sourceCols(LBound(targetHeaders) To UBound(targetHeaders))

    For i = LBound(targetHeaders) To UBound(targetHeaders)
        wsOut.Cells(1, i + 1).Value = CStr(targetHeaders(i))
        sourceCols(i) = 0

        If USE_HEADER_LOOKUP And Len(CStr(sourceHeaders(i))) > 0 Then
            sourceCols(i) = HeaderColumn(wsSrc, CStr(sourceHeaders(i)), HEADER_ROW)
        End If

        If sourceCols(i) = 0 Then
            sourceCols(i) = CLng(fallbackCols(i))
        End If
    Next i

    lastRow = LastUsedRow(wsSrc)
    outRow = 2

    If Len(CleanCellText(FIXED_TITLE)) > 0 Then
        wsOut.Cells(outRow, 1).Value = CleanCellText(FIXED_TITLE)
        wsOut.Cells(outRow, 1).Font.Underline = xlUnderlineStyleSingle
        outRow = outRow + 1
    End If

    For r = DATA_START_ROW To lastRow
        If RowHasMappedData(wsSrc, r, sourceCols) Then
            For i = LBound(targetHeaders) To UBound(targetHeaders)
                If sourceCols(i) > 0 Then
                    wsOut.Cells(outRow, i + 1).Value = CleanCellText(wsSrc.Cells(r, sourceCols(i)).Text)
                Else
                    wsOut.Cells(outRow, i + 1).Value = vbNullString
                End If
            Next i
            outRow = outRow + 1
        End If
    Next r

    wsOut.Rows(1).Font.Bold = True
    wsOut.Columns.AutoFit

    MsgBox "完成：已輸出 " & (outRow - 2) & " 筆資料到 " & OUTPUT_SHEET_NAME, vbInformation
End Sub

Private Function GetOrCreateSheet(ByVal sheetName As String) As Worksheet
    On Error Resume Next
    Set GetOrCreateSheet = ThisWorkbook.Worksheets(sheetName)
    On Error GoTo 0

    If GetOrCreateSheet Is Nothing Then
        Set GetOrCreateSheet = ThisWorkbook.Worksheets.Add(After:=ThisWorkbook.Worksheets(ThisWorkbook.Worksheets.Count))
        GetOrCreateSheet.Name = sheetName
    End If
End Function

Private Function HeaderColumn(ByVal ws As Worksheet, ByVal headerText As String, ByVal headerRow As Long) As Long
    Dim lastCol As Long
    Dim lookupKey As String
    Dim cellKey As String
    Dim c As Long

    lastCol = ws.Cells(headerRow, ws.Columns.Count).End(xlToLeft).Column
    lookupKey = NormalizeKey(headerText)

    For c = 1 To lastCol
        cellKey = NormalizeKey(ws.Cells(headerRow, c).Text)
        If cellKey = lookupKey Then
            HeaderColumn = c
            Exit Function
        End If
    Next c

    For c = 1 To lastCol
        cellKey = NormalizeKey(ws.Cells(headerRow, c).Text)
        If Len(cellKey) > 0 Then
            If InStr(1, cellKey, lookupKey, vbTextCompare) > 0 Or InStr(1, lookupKey, cellKey, vbTextCompare) > 0 Then
                HeaderColumn = c
                Exit Function
            End If
        End If
    Next c

    HeaderColumn = 0
End Function

Private Function RowHasMappedData(ByVal ws As Worksheet, ByVal rowNumber As Long, ByRef sourceCols() As Long) As Boolean
    Dim i As Long

    For i = LBound(sourceCols) To UBound(sourceCols)
        If sourceCols(i) > 0 Then
            If Len(CleanCellText(ws.Cells(rowNumber, sourceCols(i)).Text)) > 0 Then
                RowHasMappedData = True
                Exit Function
            End If
        End If
    Next i

    RowHasMappedData = False
End Function

Private Function LastUsedRow(ByVal ws As Worksheet) As Long
    Dim found As Range

    Set found = ws.Cells.Find(What:="*", LookIn:=xlFormulas, SearchOrder:=xlByRows, SearchDirection:=xlPrevious)
    If found Is Nothing Then
        LastUsedRow = 1
    Else
        LastUsedRow = found.Row
    End If
End Function

Private Function CleanCellText(ByVal value As Variant) As String
    Dim text As String

    text = CStr(value)
    text = Replace(text, Chr(13), " ")
    text = Replace(text, Chr(10), " ")
    text = Replace(text, Chr(9), " ")
    text = Application.WorksheetFunction.Trim(text)

    CleanCellText = text
End Function

Private Function NormalizeKey(ByVal value As Variant) As String
    Dim text As String

    text = LCase$(CleanCellText(value))
    text = Replace(text, " ", "")
    text = Replace(text, "_", "")
    text = Replace(text, "-", "")
    text = Replace(text, ".", "")
    text = Replace(text, "/", "")
    text = Replace(text, ":", "")
    text = Replace(text, "#", "")
    text = Replace(text, "(", "")
    text = Replace(text, ")", "")

    NormalizeKey = text
End Function
'''


def _vba_string(value: object) -> str:
    return '"' + str(value).replace('"', '""') + '"'


def _vba_boolean(value: bool) -> str:
    return "True" if value else "False"


def _vba_array_strings(values: list[str]) -> str:
    return "Array(" + ", ".join(_vba_string(value) for value in values) + ")"


def _vba_array_numbers(values: list[int]) -> str:
    return "Array(" + ", ".join(str(int(value)) for value in values) + ")"
