Option Explicit

' Generated by Invoice / Packing List VBA Generator.
' OP-compatible structure based on the original Main / TINV / TPKG macro flow.
'
' TINV item format:
'   tempArray = Array(i, Itemno, Po, QtyArray, Upce, Amt, DscArray, Title, HS, BRAND, CusItemNo)
'
' TPKG item format:
'   tempArray = Array(i, Itemno, Po, QtyArray, NW, GW, DscArray, MS)

Public INVcollection As Collection
Public PKGcollection As Collection

Private WB As Workbook
Private Inv As Worksheet
Private Pkg As Worksheet

Public Sub Main()
    Set WB = ThisWorkbook
    If SheetExists("Inv") Then
        Set Inv = WB.Worksheets("Inv")
        If WorksheetFunction.CountA(Inv.UsedRange) <> 0 Then
            Call TINV(Inv, GetOrCreateSheet("Tinv"))
        Else
            MsgBox "無法提取 TINV 資料，請確認 " & "Inv" & " 已匯入", vbExclamation
        End If
    End If
    If SheetExists("Pkg") Then
        Set Pkg = WB.Worksheets("Pkg")
        If WorksheetFunction.CountA(Pkg.UsedRange) <> 0 Then
            Call TPKG(Pkg, GetOrCreateSheet("Tpkg"), GetOrCreateSheet("Tinv"))
        End If
    End If

    MsgBox "完成：INVcollection=" & CollectionCount(INVcollection) & _
           "，PKGcollection=" & CollectionCount(PKGcollection), vbInformation
End Sub

Public Sub BuildOPTempArrays()
    Call Main
End Sub

Private Sub TINV(ByRef Dst As Worksheet, ByRef Tst As Worksheet)
    Dim headerRow As Long
    Dim ContentStartRow As Long
    Dim lastRow As Long
    Dim newRow As Long
    Dim chkCounter As Long
    Dim tempCollection As Collection

    Set tempCollection = New Collection

    headerRow = 15
    ContentStartRow = 17
    lastRow = LastUsedRow(Dst)

    Call CollectDataTinv(Dst, tempCollection, ContentStartRow, lastRow)

    Set INVcollection = tempCollection
End Sub

Private Sub CollectDataTinv(ByRef Dst As Worksheet, ByRef tempCollection As Collection, _
                            ByVal ContentStartRow As Long, ByVal lastRow As Long)
    Const HEADER_ROW As Long = 15
    Const DATA_START_ROW As Long = 17
    Const USE_HEADER_LOOKUP As Boolean = True
    Const FIXED_TITLE As String = "HAND TOOL"

    Dim targetHeaders As Variant
    Dim sourceHeaders As Variant
    Dim fallbackCols As Variant
    Dim sourceCols() As Long
    Dim lastRow As Long
    Dim i As Long

    Dim tempArray As Variant
    Dim Itemno As String
    Dim PoNo As String
    Dim Po As Variant
    Dim QtyArray As Variant
    Dim Upce As String
    Dim Amt As String
    Dim DscArray As Variant
    Dim Title As String
    Dim HS As String
    Dim BRAND As String
    Dim CusItemNo As String
    Dim LineNo As String
    Dim Dsc As String
    Dim Qty As String
    Dim unit As String

    targetHeaders = Array("Item No", "Description of Goods", "Quantity", "Unit Price", "Amount", "HS Code", "Brand")
    sourceHeaders = Array("TTI Part No", "Goods Desc", "Quantity", "Unit Price", "Amount", "HS Code", "Brand")
    fallbackCols = Array(4, 6, 8, 9, 10, 11, 12)
    ReDim sourceCols(LBound(targetHeaders) To UBound(targetHeaders))
    ResolveSourceColumns Dst, HEADER_ROW, USE_HEADER_LOOKUP, sourceHeaders, fallbackCols, sourceCols

    For i = DATA_START_ROW To lastRow
        If RowHasMappedData(Dst, i, sourceCols) Then
            Itemno = FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("item", "item no", "part", "part no", "stock", "model", "料號", "品號"))
            PoNo = FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("po", "po no", "p/o", "order", "訂單"))
            LineNo = FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("line", "line no", "項次"))
            Dsc = FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("description", "desc", "goods", "commodity", "品名", "貨名"))
            Qty = CleanNumberText(FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("qty", "quantity", "數量")))
            unit = DefaultText(FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("unit", "uom", "單位")), "PCS")
            Upce = CleanNumberText(FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("unit price", "price", "upce", "單價")))
            Amt = CleanNumberText(FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("amount", "total", "金額", "總價")))
            HS = FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("hs", "hs code", "稅則", "稅號"))
            BRAND = FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("brand", "品牌"))
            CusItemNo = FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("customer item", "cust item", "cust part", "customer part", "客戶料號"))
            Title = DefaultText(FIXED_TITLE, FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("title", "category", "分類")))

            If Len(Itemno & Dsc & Qty & Upce & Amt) = 0 Then GoTo NextTinvRow

            Po = Array(Title, PoNo, False)
            QtyArray = Array(Qty, unit)
            DscArray = Array(PrefixValue("PO# ", PoNo), PrefixValue("LINE# ", LineNo), Itemno, Dsc)

            tempArray = Array(i, Itemno, Po, QtyArray, Upce, Amt, DscArray, Title, HS, BRAND, CusItemNo)
            tempCollection.Add tempArray
        End If
NextTinvRow:
    Next i

End Sub
Private Sub TPKG(ByRef Dst As Worksheet, ByRef Tst As Worksheet, ByRef Lst As Worksheet)
    Dim headerRow As Long
    Dim ContentStartRow As Long
    Dim lastRow As Long
    Dim newRow As Long
    Dim chkCounter As Long
    Dim tempCollection As Collection

    Set tempCollection = New Collection

    headerRow = 15
    ContentStartRow = 17
    lastRow = LastUsedRow(Dst)

    Call CollectDataTpkg(Dst, tempCollection, ContentStartRow, lastRow)

    Set PKGcollection = tempCollection
End Sub

Private Sub CollectDataTpkg(ByRef Dst As Worksheet, ByRef tempCollection As Collection, _
                            ByVal ContentStartRow As Long, ByVal lastRow As Long)
    Const HEADER_ROW As Long = 15
    Const DATA_START_ROW As Long = 17
    Const USE_HEADER_LOOKUP As Boolean = True
    Const FIXED_TITLE As String = ""

    Dim targetHeaders As Variant
    Dim sourceHeaders As Variant
    Dim fallbackCols As Variant
    Dim sourceCols() As Long
    Dim lastRow As Long
    Dim i As Long

    Dim tempArray As Variant
    Dim Itemno As String
    Dim PoNo As String
    Dim Po As Variant
    Dim QtyArray As Variant
    Dim NW As String
    Dim GW As String
    Dim DscArray As Variant
    Dim MS As String
    Dim Title As String
    Dim Cno As String
    Dim CTN As String
    Dim Dsc As String
    Dim UQty As String
    Dim Qty As String
    Dim unit As String
    Dim CustPo As String

    targetHeaders = Array("Marks & Nos.", "Description of Goods", "Quantity", "Net Weight", "Gross Weight", "Measurement")
    sourceHeaders = Array("Marks & Nos.", "Description of Goods", "Quantity", "N.W.", "G.W.", "Measurement")
    fallbackCols = Array(1, 5, 8, 10, 11, 12)
    ReDim sourceCols(LBound(targetHeaders) To UBound(targetHeaders))
    ResolveSourceColumns Dst, HEADER_ROW, USE_HEADER_LOOKUP, sourceHeaders, fallbackCols, sourceCols

    For i = DATA_START_ROW To lastRow
        If RowHasMappedData(Dst, i, sourceCols) Then
            Itemno = FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("item", "item no", "part", "part no", "stock", "model", "料號", "品號"))
            CustPo = FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("cust po", "customer po", "po", "po no", "p/o", "訂單"))
            PoNo = FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("tti po", "po number", "po no", "po", "訂單"))
            Dsc = FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("description", "desc", "goods", "commodity", "品名", "貨名"))
            Cno = DefaultText(FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("marks", "marks nos", "carton no", "ctn no", "case no", "箱號", "嘜頭")), "")
            CTN = DefaultText(CleanNumberText(FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("ctn", "carton", "packages", "package", "箱數", "件數"))), "1")
            UQty = CleanNumberText(FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("unit qty", "uqty", "quantity", "qty", "數量")))
            Qty = DefaultText(CleanNumberText(FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("qty", "quantity", "數量"))), UQty)
            unit = DefaultText(FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("unit", "uom", "單位")), "PCS")
            NW = CleanNumberText(FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("net weight", "n.w", "nw", "淨重")))
            GW = CleanNumberText(FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("gross weight", "g.w", "gw", "毛重")))
            MS = CleanNumberText(FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("measurement", "measure", "cbm", "volume", "材積")))
            Title = DefaultText(FIXED_TITLE, FirstMappedValue(Dst, i, sourceCols, targetHeaders, Array("title", "category", "分類")))

            If Len(Itemno & Dsc & Qty & NW & GW & Cno) = 0 Then GoTo NextTpkgRow

            Po = Array(Title, False, Cno, Val(CTN))
            QtyArray = Array(UQty, Qty, unit)
            DscArray = Array(PrefixValue("CUST P/O# ", CustPo), PrefixValue("TTI PO NO. ", PoNo), PrefixValue("CUST PART NO. ", Itemno), Dsc)

            tempArray = Array(i, Itemno, Po, QtyArray, NW, GW, DscArray, MS)
            tempCollection.Add tempArray
        End If
NextTpkgRow:
    Next i

End Sub

Private Sub ResolveSourceColumns(ByVal ws As Worksheet, ByVal headerRow As Long, _
                                 ByVal useHeaderLookup As Boolean, ByVal sourceHeaders As Variant, _
                                 ByVal fallbackCols As Variant, ByRef sourceCols() As Long)
    Dim i As Long

    For i = LBound(sourceHeaders) To UBound(sourceHeaders)
        sourceCols(i) = 0

        If useHeaderLookup And Len(CStr(sourceHeaders(i))) > 0 Then
            sourceCols(i) = HeaderColumn(ws, CStr(sourceHeaders(i)), headerRow)
        End If

        If sourceCols(i) = 0 Then
            sourceCols(i) = CLng(fallbackCols(i))
        End If
    Next i
End Sub

Private Function FirstMappedValue(ByVal ws As Worksheet, ByVal rowNumber As Long, _
                                  ByRef sourceCols() As Long, ByVal targetHeaders As Variant, _
                                  ByVal keywords As Variant) As String
    Dim i As Long
    Dim k As Long
    Dim headerKey As String
    Dim keywordKey As String

    For i = LBound(targetHeaders) To UBound(targetHeaders)
        If sourceCols(i) > 0 Then
            headerKey = NormalizeKey(CStr(targetHeaders(i)))
            For k = LBound(keywords) To UBound(keywords)
                keywordKey = NormalizeKey(CStr(keywords(k)))
                If Len(keywordKey) > 0 Then
                    If InStr(1, headerKey, keywordKey, vbTextCompare) > 0 Or _
                       InStr(1, keywordKey, headerKey, vbTextCompare) > 0 Then
                        FirstMappedValue = CleanCellText(ws.Cells(rowNumber, sourceCols(i)).Text)
                        Exit Function
                    End If
                End If
            Next k
        End If
    Next i

    FirstMappedValue = vbNullString
End Function

Private Function PrefixValue(ByVal prefixText As String, ByVal value As String) As String
    value = CleanCellText(value)
    If Len(value) = 0 Then
        PrefixValue = vbNullString
    Else
        PrefixValue = prefixText & value
    End If
End Function

Private Function CleanNumberText(ByVal value As String) As String
    Dim i As Long
    Dim ch As String
    Dim result As String

    value = CleanCellText(value)
    For i = 1 To Len(value)
        ch = Mid$(value, i, 1)
        If (ch >= "0" And ch <= "9") Or ch = "." Or ch = "-" Then
            result = result & ch
        End If
    Next i

    CleanNumberText = result
End Function

Private Function DefaultText(ByVal value As String, ByVal fallback As String) As String
    value = CleanCellText(value)
    If Len(value) = 0 Then
        DefaultText = fallback
    Else
        DefaultText = value
    End If
End Function

Private Function CollectionCount(ByVal items As Collection) As Long
    On Error Resume Next
    CollectionCount = items.Count
    If Err.Number <> 0 Then CollectionCount = 0
    On Error GoTo 0
End Function

Private Function SheetExists(ByVal sheetName As String) As Boolean
    Dim ws As Worksheet

    On Error Resume Next
    Set ws = ThisWorkbook.Worksheets(sheetName)
    On Error GoTo 0

    SheetExists = Not ws Is Nothing
End Function

Private Function HeaderColumn(ByVal ws As Worksheet, ByVal headerText As String, ByVal headerRow As Long) As Long
    Dim lastCol As Long
    Dim lookupKey As String
    Dim cellKey As String
    Dim c As Long

    lastCol = ws.Cells(headerRow, ws.Columns.Count).End(xlToLeft).Column
    lookupKey = NormalizeKey(headerText)

    For c = 1 To lastCol
        cellKey = NormalizeKey(ws.Cells(headerRow, c).Text)
        If cellKey = lookupKey Then
            HeaderColumn = c
            Exit Function
        End If
    Next c

    For c = 1 To lastCol
        cellKey = NormalizeKey(ws.Cells(headerRow, c).Text)
        If Len(cellKey) > 0 Then
            If InStr(1, cellKey, lookupKey, vbTextCompare) > 0 Or InStr(1, lookupKey, cellKey, vbTextCompare) > 0 Then
                HeaderColumn = c
                Exit Function
            End If
        End If
    Next c

    HeaderColumn = 0
End Function

Private Function RowHasMappedData(ByVal ws As Worksheet, ByVal rowNumber As Long, ByRef sourceCols() As Long) As Boolean
    Dim i As Long

    For i = LBound(sourceCols) To UBound(sourceCols)
        If sourceCols(i) > 0 Then
            If Len(CleanCellText(ws.Cells(rowNumber, sourceCols(i)).Text)) > 0 Then
                RowHasMappedData = True
                Exit Function
            End If
        End If
    Next i

    RowHasMappedData = False
End Function

Private Function LastUsedRow(ByVal ws As Worksheet) As Long
    Dim found As Range

    Set found = ws.Cells.Find(What:="*", LookIn:=xlFormulas, SearchOrder:=xlByRows, SearchDirection:=xlPrevious)
    If found Is Nothing Then
        LastUsedRow = 1
    Else
        LastUsedRow = found.Row
    End If
End Function

Private Function CleanCellText(ByVal value As Variant) As String
    Dim text As String

    text = CStr(value)
    text = Replace(text, Chr(13), " ")
    text = Replace(text, Chr(10), " ")
    text = Replace(text, Chr(9), " ")
    text = Application.WorksheetFunction.Trim(text)

    CleanCellText = text
End Function

Private Function NormalizeKey(ByVal value As Variant) As String
    Dim text As String

    text = LCase$(CleanCellText(value))
    text = Replace(text, " ", "")
    text = Replace(text, "_", "")
    text = Replace(text, "-", "")
    text = Replace(text, ".", "")
    text = Replace(text, "/", "")
    text = Replace(text, ":", "")
    text = Replace(text, "#", "")
    text = Replace(text, "&", "")
    text = Replace(text, "'", "")
    text = Replace(text, "(", "")
    text = Replace(text, ")", "")

    NormalizeKey = text
End Function
